import type {StoryboardBeat} from '../../core/src/schema';
import {renderV2Beat} from './v2-markup';

export {escapeHtml, markupIdentity} from './v2-markup';

export const beatMarkup = (beat: StoryboardBeat): string => renderV2Beat(beat);

export const sharedCss = `
:root{--bg:#07101f;--fg:#f8fafc;--accent:#5eead4}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;font-family:Inter,"Noto Sans SC","Microsoft YaHei",system-ui,sans-serif}.stage{position:relative;width:100vw;height:100vh;overflow:hidden}.source{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.overlay{position:absolute;inset:0;pointer-events:none}.beat{position:absolute;inset:0;color:var(--beat-fg)}.beat__motion{position:absolute;inset:0;opacity:0;overflow:hidden}.beat__rail{position:absolute;left:6%;right:6%;bottom:18%;height:6px;border-radius:99px;background:linear-gradient(90deg,var(--beat-accent),var(--beat-line));transform-origin:left center}em{font-style:normal;font-size:18px;font-weight:900;letter-spacing:.14em;color:var(--beat-line)}h2,h3,p{margin:0}mark{display:inline-flex;padding:10px 14px;border-radius:999px;background:var(--beat-accent);color:var(--beat-canvas);font-weight:950}
.dual-rail,.thesis-proof{position:absolute;inset:7% 5% 18%;display:grid;grid-template-columns:27% 27%;justify-content:space-between}.dual-rail aside,.thesis-proof aside,.command-panel{position:relative;padding:28px 25px;border-radius:26px;background:color-mix(in srgb,var(--beat-surface) 92%,transparent);border:1px solid color-mix(in srgb,var(--beat-line) 55%,transparent)}.dual-rail h2,.thesis-proof h2{margin:20px 0;font-size:43px;line-height:1}.numbered-item{display:grid;grid-template-columns:34px 1fr;gap:12px;margin-top:18px}.numbered-item>b{height:34px;display:grid;place-items:center;border-radius:10px;background:var(--beat-accent);color:var(--beat-canvas)}.numbered-item strong,.numbered-item small{display:block}.numbered-item small{margin-top:6px;color:var(--beat-muted)}.dual-rail mark{position:absolute;left:25px;right:25px;bottom:24px;border-radius:12px}.thesis-proof p{margin:24px 0;font-size:27px;line-height:1.35}.thesis-proof small{display:block;margin-top:18px;color:var(--beat-muted)}
.bidirectional,.metrics,.semantic-doodle{position:absolute;inset:7% 5% 18%}.bidirectional .node{position:absolute;top:28%;width:27%;padding:28px;border-radius:28px;background:var(--beat-surface);border:2px solid var(--beat-line)}.node--left{left:0}.node--right{right:0}.bidirectional h3{margin-top:18px;font-size:48px}.flow-lines{position:absolute;left:34%;right:34%;top:25%;display:grid;gap:150px;text-align:center;font-size:24px;font-weight:900;color:var(--beat-accent)}.bidirectional>mark{position:absolute;left:50%;bottom:10%;transform:translateX(-50%)}
.command-panel{position:absolute;top:7%;bottom:18%;width:27%}.beat[data-placement=right] .command-panel{right:5%}.beat:not([data-placement=right]) .command-panel{left:5%}.command-panel h2{margin:18px 0;font-size:35px}.command-panel ol{padding:0;display:grid;gap:10px;list-style:none}.command-panel li{padding:13px;border-radius:13px;background:var(--beat-card);font-weight:800}.command-panel li span{margin-right:10px;color:var(--beat-accent)}.command-panel mark{position:absolute;right:24px;bottom:24px}
.pipeline,.before-after,.evidence,.signal-route{position:absolute;inset:7% 6% 18%;padding:32px;border-radius:30px;background:color-mix(in srgb,var(--beat-canvas) 93%,transparent)}.pipeline h2{margin-top:14px;font-size:54px}.pipeline__stages{display:grid;grid-template-columns:repeat(4,1fr);gap:18px;margin-top:9%}.pipeline article{min-height:205px;padding:26px 22px;border-radius:24px;background:var(--beat-card);border:2px solid var(--beat-line)}.pipeline article b,.pipeline article strong{display:block}.pipeline article strong{margin-top:50px;font-size:30px}.pipeline>mark{position:absolute;right:32px;bottom:28px}
.before-after{display:grid;grid-template-columns:1fr 8px 1fr;gap:26px;align-items:center}.before-after section{padding:7%;height:75%;border-radius:26px;background:var(--beat-surface)}.before-after section h2{margin-top:90px;font-size:58px}.scrubber{height:90%;border-radius:99px;background:var(--beat-accent);box-shadow:0 0 34px var(--beat-accent)}.before-after mark{position:absolute;left:50%;bottom:25px;transform:translateX(-50%)}
.evidence{display:grid;grid-template-columns:1.65fr .72fr;gap:30px}.evidence figure{position:relative;margin:0;overflow:hidden;border-radius:28px;background:#fff;border:3px solid var(--beat-line)}.evidence img{width:100%;height:100%;object-fit:contain}.evidence figcaption{position:absolute;left:20px;bottom:18px;padding:9px 13px;border-radius:10px;background:var(--beat-canvas);color:var(--beat-fg);font-weight:850}.evidence aside{align-self:center;padding:30px 26px;border-radius:26px;background:var(--beat-surface)}.evidence h2{margin-top:22px;font-size:39px;line-height:1.08}
.metrics{display:grid;grid-template-columns:27% 27%;justify-content:space-between;gap:36%}.metrics article{align-self:center;padding:28px 25px;border-radius:28px;background:var(--beat-surface);border:2px solid var(--beat-line)}.metrics article div{display:flex;align-items:baseline;gap:8px;margin-top:24px}.metrics strong{font-size:78px;line-height:.9}.metrics p{margin-top:18px;font-size:24px}.metrics mark{margin-top:18px;font-size:14px}
.signal-route{display:grid;align-content:center}.route-nodes{display:flex;align-items:center;justify-content:center;gap:15px;margin-top:10%;font-size:22px;font-weight:900}.route-nodes span{min-width:135px;padding:22px 14px;border-radius:22px;background:var(--beat-surface);border:3px solid var(--beat-line);text-align:center}.route-nodes span b{display:block;margin-bottom:10px;color:var(--beat-accent)}.route-nodes i{font-style:normal;font-size:32px;color:var(--beat-accent)}.signal-route>mark{position:absolute;left:50%;bottom:35px;transform:translateX(-50%)}
.semantic-doodle{display:grid;grid-template-columns:27% 1fr;gap:3%;padding:24px}.semantic-doodle aside{padding:28px;border-radius:28px;background:var(--beat-surface)}.semantic-doodle aside h2{margin-top:25px;font-size:43px}.semantic-doodle aside p{margin-top:20px;font-size:24px}.semantic-doodle svg{width:100%;height:100%;padding:20px;border-radius:30px;background:var(--beat-card)}.semantic-doodle>mark{position:absolute;right:24px;bottom:22px;background:var(--doodle-accent)}
`;
